---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pv
  labels:
    app: grafana
    tier: web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: graf-svc
  labels:
    app: grafana
    tier: web
spec:
  ports:
    - nodePort: 30110
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
    tier: web
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: graf-deploy
  labels:
    app: grafana
    tier: web
spec:
  selector:
    matchLabels:
      app: grafana
      tier: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: web
    spec:
      containers:
      - image: neelaksh1/grafana:v1
        name: graf-conti
        ports:
        - containerPort: 3000
          name: graf-conti
        volumeMounts:
        - name: graf-persistent-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: graf-persistent-storage
        persistentVolumeClaim:
          claimName: graf-pv
