apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pv
  labels:
    app: prometheus
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: prom-svc
  labels:
    app: prometheus
spec:
  ports:
    - nodePort: 30010
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
    tier: web
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-script
data: 
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
    rule_files:
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: [ 'loacalhost:9090' ]
    - job_name: 'node_exporter'
      static_configs:
      - targets: [ '192.168.56.3:9100' ]
        labels:
          app: 'prometheus'


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-deploy
  labels:
    app: container
spec:
  selector:
    matchLabels:
      app: prometheus
      tier: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
        tier: web
    spec:
      containers:
      - image: neelaksh1/prometheus:v1
        name: prom-conti
        ports:
        - containerPort: 9090
          name: prom-conti
        volumeMounts:
        - name:prom-pvc
          mountPath: /etc/prom
         - name: prometheus-script
           mountPath: /etc/prometheus/prometheus.yml
           subPath: prometheus.yml
      volumes:
      - name: prom-pvc
        persistentVolumeClaim:
          claimName: prom-pv
      - name: prometheus-script
        configMap:
          name: prom-script
          defaultMode: 0744
---